# Generated by Django 4.1.7 on 2024-05-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectMarks',
            new_name='SubjectMark',
        ),
        migrations.AlterModelOptions(
            name='subjectmark',
            options={'ordering': ['student']},
        ),
    ]
