# Generated by Django 4.1.7 on 2024-05-21 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentid', to='card.student'),
        ),
    ]
