# Generated by Django 4.1.7 on 2024-05-21 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_subjectmark_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student1_id', to='card.studentid'),
        ),
        migrations.AlterField(
            model_name='subjectmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student1_id', to='card.student'),
        ),
    ]
