# Generated by Django 4.1.7 on 2024-06-08 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_subjectmark_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_generation', models.DateField(auto_created=True)),
                ('rank', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentranks', to='card.student')),
            ],
            options={
                'unique_together': {('rank', 'date_of_generation')},
            },
        ),
    ]
