# Generated by Django 4.1.7 on 2024-06-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_studentrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrank',
            name='date_of_generation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
