# Generated by Django 4.1.7 on 2024-06-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_alter_studentrank_date_of_generation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentrank',
            options={'ordering': ['rank']},
        ),
    ]
